version: '3.9'
services:
  card_db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: 'card-manager'
      POSTGRES_USER: 'weinber'
      POSTGRES_PASSWORD: 'weinber'
    ports:
      - 5431:5432
    expose:
      - '5431'
    volumes:
      - card:/var/lib/postgresql/data
volumes:
  card: